# Generated by Django 3.2.12 on 2024-03-27 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_owner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ctaegory',
            new_name='Cataegory',
        ),
    ]
