# Generated by Django 3.2.12 on 2024-03-27 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_rename_ctaegory_cataegory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cataegory',
            new_name='Category',
        ),
    ]
