# Generated by Django 3.2.12 on 2024-03-27 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
